# Tomcat配置 #
server:
  port: 8082

# Spring配置 #
spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/blackdog?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 990708
        # druid连接池
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        # 初始化连接 #
        initialSize: 1
        # 最大活动连接 #
        maxActive: 20
        # 最大等待时间 #
        maxWait: 60000
        # 最小空闲连接 #
        minIdle: 1
        # 多少秒运行一次空闲连接回收器 30秒 #
        timeBetweenEvictionRunsMillis: 60000
        # 连接空闲多久被回收 30分钟 #
        minEvictableIdleTimeMillis: 1800000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
        mode: HTML5
    redis:
      host: localhost
      port: 6379

mybatis:
  config-location: /mapper/*.xml

# 打印sql #
logging:
  level:
    com.lizhigang: debug


